# Generated by Django 6.0.2 on 2026-07-16 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(db_index=True, max_length=255)),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                ("scaler_type", models.CharField(max_length=100)),
                ("contamination", models.FloatField(blank=True, null=True)),
                ("total_records", models.IntegerField()),
                ("anomaly_count", models.IntegerField()),
                ("dataset_type", models.CharField(default="unlabelled", max_length=20)),
                (
                    "target_column",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("model_path", models.CharField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(db_index=True, max_length=100)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("isolation_forest", "Isolation Forest"),
                            ("lof", "Local Outlier Factor"),
                            ("one_class_svm", "One Class SVM"),
                            ("dbscan", "DBSCAN"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dataset_name", models.CharField(db_index=True, max_length=255)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("anomaly_count", models.IntegerField(default=0)),
                ("model_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadedDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(db_index=True, max_length=255)),
                ("columns", models.JSONField()),
                ("results", models.JSONField()),
                ("total", models.IntegerField(default=0)),
                ("anomalies", models.IntegerField(default=0)),
                ("normal", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(db_index=True, max_length=255)),
                ("total", models.IntegerField()),
                ("normal", models.IntegerField()),
                ("anomalies", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
