# Generated by Django 6.0.2 on 2026-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomaly", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("columns", models.JSONField()),
                ("results", models.JSONField()),
                ("total", models.IntegerField(default=0)),
                ("anomalies", models.IntegerField(default=0)),
                ("normal", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
