# Generated by Django 6.0.2 on 2026-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomaly", "0003_anomalyresult_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=100)),
                ("scaler_type", models.CharField(max_length=100)),
                ("contamination", models.FloatField(blank=True, null=True)),
                ("total_records", models.IntegerField()),
                ("anomaly_count", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
