# Generated by Django 6.0.2 on 2026-05-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomaly", "0004_detectionhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="detectionhistory",
            name="accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionhistory",
            name="dataset_type",
            field=models.CharField(default="unlabelled", max_length=20),
        ),
        migrations.AddField(
            model_name="detectionhistory",
            name="f1_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionhistory",
            name="model_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="detectionhistory",
            name="precision",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionhistory",
            name="recall",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="detectionhistory",
            name="target_column",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
