# Generated by Django 6.0.2 on 2026-05-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomaly", "0005_detectionhistory_accuracy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("isolation_forest", "Isolation Forest"),
                            ("lof", "Local Outlier Factor"),
                            ("one_class_svm", "One Class SVM"),
                            ("dbscan", "DBSCAN"),
                        ],
                        max_length=50,
                    ),
                ),
                ("dataset_name", models.CharField(max_length=255)),
                ("precision", models.FloatField(blank=True, null=True)),
                ("recall", models.FloatField(blank=True, null=True)),
                ("f1_score", models.FloatField(blank=True, null=True)),
                ("anomaly_count", models.IntegerField(default=0)),
                ("model_path", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
